[project]
name = 'parakeet_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.audit_log]
path = 'contracts/audit_log.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_validation_store]
path = 'contracts/data_validation_store.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting_with_vote_receipt]
path = 'contracts/voting_with_vote_receipt.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
